import type { Article } from '@/types'

export const MOCK_ARTICLES: Article[] = [
  {
    id: 1,
    title: 'OpenAI 发布 GPT-5，多模态能力大幅提升，推理速度提升 3 倍',
    summary: 'OpenAI 正式发布 GPT-5 模型，在数学推理、代码生成和多模态理解方面取得重大突破。新模型在 MMLU 基准测试中达到 92.3% 的准确率，较 GPT-4 提升约 8 个百分点。',
    content: `OpenAI 正式发布 GPT-5 模型，在数学推理、代码生成和多模态理解方面取得重大突破。新模型在 MMLU 基准测试中达到 92.3% 的准确率，较 GPT-4 提升约 8 个百分点。

**核心技术突破**

GPT-5 采用全新的混合专家架构（MoE），在保持推理质量的同时将推理速度提升了 3 倍。多模态能力方面，GPT-5 支持视频流输入（最长 30 分钟），并能实时处理音频、图像和文本的混合输入。

**商业化进展**

API 调用价格较 GPT-4o 下降 50%，企业版同步发布，含私有化部署选项。OpenAI 表示，GPT-5 将在未来两周内向所有 ChatGPT Plus 用户开放。

**行业影响**

多位业内专家表示，GPT-5 的发布将进一步加速企业 AI 应用落地，特别是在代码辅助、文档处理和客户服务领域。`,
    contentEn: `OpenAI has officially released GPT-5, achieving major breakthroughs in mathematical reasoning, code generation, and multimodal understanding. The new model achieves 92.3% accuracy on the MMLU benchmark, approximately 8 percentage points higher than GPT-4.

**Core Technical Breakthroughs**

GPT-5 adopts a new Mixture of Experts (MoE) architecture, tripling inference speed while maintaining reasoning quality. In terms of multimodal capabilities, GPT-5 supports video stream input (up to 30 minutes) and can process mixed inputs of audio, images, and text in real-time.

**Commercialization Progress**

API call prices are 50% lower than GPT-4o, with an enterprise version released simultaneously including private deployment options. OpenAI stated that GPT-5 will be available to all ChatGPT Plus users within the next two weeks.`,
    domain: 'tech',
    region: 'international',
    source: 'TechCrunch',
    publishTime: '2小时前',
    aiScore: 95,
    sentiment: 'positive',
    radarWords: ['GPT-5', 'OpenAI'],
    tags: ['OpenAI', 'GPT-5', '大模型', '多模态'],
    isAiTranslated: true,
    likeCount: 128,
    collectCount: 56,
    isLiked: false,
    isCollected: false,
    aiSummary: 'OpenAI 正式发布 GPT-5，在数学推理、代码生成和多模态理解方面取得重大突破。新模型推理速度提升 3 倍，API 价格下降 50%，将加速企业 AI 应用落地。',
    aiKeyPoints: [
      '多模态理解能力较 GPT-4o 提升 3 倍，支持视频流输入（最长 30 分钟）',
      'API 调用价格下降 50%，企业版同步发布，含私有化部署选项',
      '推理速度提升 2 倍，平均延迟降至 200ms 以内',
    ],
    aiQuestions: [
      '这项技术的商业化落地难点？',
      '国内有哪些类似竞争者？',
      '对开发者意味着什么？',
      '技术指标提升了多少？',
    ],
    knowledgeTree: [
      {
        id: '1',
        title: 'GPT 系列发展历程',
        description: 'OpenAI 从 GPT-1 到 GPT-5 的技术演进',
        date: '2018-2025',
        children: [
          { id: '1-1', title: 'GPT-4 发布', description: '2023年3月，多模态能力首次引入', date: '2023-03' },
          { id: '1-2', title: 'GPT-4o 发布', description: '2024年5月，原生多模态，速度提升', date: '2024-05' },
          { id: '1-3', title: 'GPT-5 发布', description: '2025年，MoE架构，能力全面跃升', date: '2025' },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Anthropic 完成 40 亿美元 D 轮融资，估值达 180 亿美元',
    summary: 'Anthropic 宣布完成新一轮 40 亿美元融资，由 Google 领投，亚马逊跟投，公司估值达到 180 亿美元。本轮融资将主要用于 Claude 4 模型研发及企业级产品扩张。',
    domain: 'tech',
    region: 'international',
    source: 'The Information',
    publishTime: '5小时前',
    aiScore: 91,
    sentiment: 'positive',
    tags: ['Anthropic', 'Claude', '融资', 'AI'],
    isAiTranslated: true,
    likeCount: 89,
    collectCount: 34,
    isLiked: false,
    isCollected: false,
    aiSummary: 'Anthropic 完成 40 亿美元 D 轮融资，Google 领投，估值达 180 亿美元，将用于 Claude 4 研发。',
    aiKeyPoints: [
      'Google 领投，亚马逊跟投，融资规模 40 亿美元',
      '公司估值达 180 亿美元，较上轮提升约 50%',
      '资金将用于 Claude 4 模型研发及企业级产品扩张',
    ],
    aiQuestions: [
      '这件事对 AI 竞争格局有什么影响？',
      '国内有哪些类似竞争者？',
      'Claude 与 GPT 的差异化在哪里？',
    ],
  },
  {
    id: 3,
    title: '美联储宣布维持利率不变，暗示年内可能降息两次',
    summary: '美联储在最新议息会议上决定维持联邦基金利率在 5.25%-5.5% 区间不变，但点阵图显示委员们预计年内将有两次降息，市场对此反应积极，道琼斯指数上涨 1.2%。',
    domain: 'finance',
    region: 'international',
    source: '财联社',
    publishTime: '3小时前',
    aiScore: 88,
    sentiment: 'positive',
    radarWords: ['美联储'],
    tags: ['美联储', '降息', '利率', '美股'],
    likeCount: 203,
    collectCount: 87,
    isLiked: false,
    isCollected: false,
    aiSummary: '美联储维持利率不变，但点阵图暗示年内两次降息，市场反应积极，道指涨 1.2%。',
    aiKeyPoints: [
      '联邦基金利率维持 5.25%-5.5% 不变',
      '点阵图显示年内预计降息两次，每次 25 个基点',
      '道琼斯指数上涨 1.2%，纳斯达克涨 1.8%',
    ],
    aiQuestions: [
      '这件事对 A 股有什么影响？',
      '降息对哪些行业最有利？',
      '人民币汇率会如何变化？',
    ],
  },
  {
    id: 4,
    title: '英伟达 H200 GPU 供货紧张，台积电扩产计划提前',
    summary: '受全球 AI 算力需求持续爆发影响，英伟达 H200 GPU 交货周期已延长至 52 周，台积电宣布将 CoWoS 先进封装产能扩张计划提前至 2026 年第二季度，预计产能提升 60%。',
    domain: 'tech',
    region: 'international',
    source: '36Kr',
    publishTime: '5小时前',
    aiScore: 85,
    sentiment: 'neutral',
    tags: ['英伟达', '台积电', 'GPU', 'AI算力'],
    isAiTranslated: true,
    likeCount: 156,
    collectCount: 62,
    isLiked: false,
    isCollected: false,
    aiSummary: '英伟达 H200 GPU 交货周期延至 52 周，台积电提前扩产，AI 算力供需矛盾短期难以缓解。',
    aiKeyPoints: [
      'H200 GPU 交货周期延长至 52 周，较去年同期增加 20 周',
      '台积电 CoWoS 产能扩张计划提前至 2026 年 Q2',
      '预计产能提升 60%，但仍难满足短期需求',
    ],
    aiQuestions: [
      '国内算力芯片有哪些替代方案？',
      '哪些 A 股公司会受益？',
      '这对 AI 创业公司有什么影响？',
    ],
  },
  {
    id: 5,
    title: '某头部互联网公司发布 2025 年年报，AI 业务营收同比增长 187%',
    summary: '某头部互联网公司发布 2025 年全年财务报告，总营收达 4,820 亿元，同比增长 23%。其中 AI 相关业务（云计算、大模型 API、智能硬件）营收 680 亿元，同比增长 187%，成为最大增长引擎。',
    domain: 'finance',
    region: 'domestic',
    source: '第一财经',
    publishTime: '12小时前',
    aiScore: 82,
    sentiment: 'positive',
    tags: ['互联网', 'AI', '财报', '云计算'],
    likeCount: 94,
    collectCount: 41,
    isLiked: false,
    isCollected: false,
    aiSummary: '头部互联网公司 AI 业务营收增长 187%，成为最大增长引擎，云计算和大模型 API 表现亮眼。',
    aiKeyPoints: [
      '总营收 4,820 亿元，同比增长 23%',
      'AI 相关业务营收 680 亿元，同比增长 187%',
      '大模型 API 调用量同比增长 450%',
    ],
    aiQuestions: [
      '这件事对 A 股有什么影响？',
      '与竞争对手相比如何？',
      'AI 业务的主要增长来源是什么？',
    ],
  },
  {
    id: 6,
    title: 'A 股三大指数集体收涨，科技板块领涨，半导体指数单日涨幅 3.8%',
    summary: '今日 A 股市场整体表现强劲，上证指数收涨 1.15%，深证成指涨 1.43%，创业板指涨 1.89%。科技板块全面走强，半导体、AI 算力、数据要素等方向涨幅居前。',
    domain: 'finance',
    region: 'domestic',
    source: '东方财富',
    publishTime: '4小时前',
    aiScore: 72,
    sentiment: 'positive',
    radarWords: ['A股'],
    tags: ['A股', '半导体', '科技', '行情'],
    likeCount: 67,
    collectCount: 23,
    isLiked: false,
    isCollected: false,
    aiSummary: 'A 股三大指数全线上涨，科技板块领涨，半导体指数单日涨幅 3.8%，北向资金净流入。',
    aiKeyPoints: [
      '上证指数涨 1.15%，深证成指涨 1.43%，创业板指涨 1.89%',
      '半导体指数单日涨幅 3.8%，创近期新高',
      '北向资金净流入 48 亿元',
    ],
    aiQuestions: [
      '哪些个股值得关注？',
      '这轮上涨的主要驱动因素？',
      '后市如何判断？',
    ],
  },
  {
    id: 7,
    title: '工信部发布《人工智能大模型安全评估规范》，2026 年 Q3 起正式执行',
    summary: '工信部就《人工智能大模型安全评估规范》公开征求意见，要求所有公开可用大模型须通过安全评估，覆盖内容安全、数据安全、算法透明度三大维度，2026 年 Q3 起正式执行。',
    domain: 'policy',
    region: 'domestic',
    source: '工信部官网',
    publishTime: '1天前',
    aiScore: 84,
    sentiment: 'neutral',
    radarWords: ['大模型', '政策监管'],
    tags: ['工信部', '大模型', '安全', '政策'],
    likeCount: 112,
    collectCount: 78,
    isLiked: false,
    isCollected: false,
    aiSummary: '工信部发布大模型安全评估规范，覆盖内容安全、数据安全、算法透明度，2026 年 Q3 正式执行。',
    aiKeyPoints: [
      '覆盖所有面向公众提供服务的大模型，包括 API 调用形式',
      '评估内容包括：内容安全、数据安全、算法透明度三大维度',
      '2026 年 Q3 起正式执行，现有模型需在 6 个月内完成评估',
    ],
    aiQuestions: [
      '这项政策的执行时间表？',
      '对哪些企业影响最大？',
      '合规要求有哪些？',
    ],
  },
  {
    id: 8,
    title: '北京市智慧城市建设项目（二期）公开招标，预算 12.8 亿元',
    summary: '北京市御天区智慧城市建设项目二期正式发布招标公告，项目总预算 12.8 亿元，分为基础设施、数字平台、智能应用三个标段，投标截止日期为 4 月 15 日。',
    domain: 'commerce',
    region: 'domestic',
    source: '中国政府采购网',
    publishTime: '30分钟前',
    aiScore: 91,
    sentiment: 'positive',
    radarWords: ['招投标'],
    tags: ['招投标', '智慧城市', '北京', '政府采购'],
    isAiTranslated: false,
    likeCount: 45,
    collectCount: 89,
    isLiked: false,
    isCollected: false,
    aiSummary: '北京市智慧城市二期项目招标，总预算 12.8 亿，分三个标段，截止 4 月 15 日。',
    aiKeyPoints: [
      '基础设施标段：预算 6.2 亿，要求建筑业一级资质',
      '数字平台标段：预算 3.8 亿，需提供云计算、大数据、AI 中台整体解决方案',
      '智能应用标段：预算 2.8 亿，聚焦城市大脑、智慧交通、智慧政务',
    ],
    aiQuestions: [
      '这个项目的招标条件？',
      '有哪些潜在竞争对手？',
      '项目的商业价值分析',
    ],
  },
  {
    id: 9,
    title: '欧盟 AI 法案正式生效，高风险 AI 须合规审查',
    summary: '欧盟《人工智能法案》正式生效，对高风险 AI 系统实施强制合规审查，违规最高罚款 3000 万欧元，出海企业需重点关注。',
    domain: 'policy',
    region: 'international',
    source: 'EU Commission',
    publishTime: '8小时前',
    aiScore: 78,
    sentiment: 'neutral',
    tags: ['欧盟', 'AI法案', '合规', '监管'],
    isAiTranslated: true,
    likeCount: 134,
    collectCount: 67,
    isLiked: false,
    isCollected: false,
    aiSummary: '欧盟 AI 法案生效，高风险 AI 须强制合规审查，违规最高罚款 3000 万欧元。',
    aiKeyPoints: [
      '高风险 AI 分类包括：医疗、教育、招聘、执法等 8 大领域',
      '企业须建立 AI 风险管理体系并向监管机构备案',
      '违规最高罚款 3000 万欧元或全球营收的 6%',
    ],
    aiQuestions: [
      '哪些中国企业需要关注？',
      '合规成本大概是多少？',
      '与美国 AI 监管有何不同？',
    ],
  },
  {
    id: 10,
    title: '华为发布盘古大模型 5.0，多项指标超越 GPT-4',
    summary: '华为在 2025 年开发者大会上正式发布盘古大模型 5.0，在中文理解、代码生成、科学计算等多项基准测试中超越 GPT-4，并宣布向企业客户开放 API 接口。',
    domain: 'tech',
    region: 'domestic',
    source: '华为官方',
    publishTime: '6小时前',
    aiScore: 88,
    sentiment: 'positive',
    radarWords: ['大模型'],
    tags: ['华为', '盘古', '大模型', 'AI'],
    likeCount: 267,
    collectCount: 123,
    isLiked: false,
    isCollected: false,
    aiSummary: '华为盘古大模型 5.0 发布，多项指标超越 GPT-4，向企业客户开放 API。',
    aiKeyPoints: [
      '中文理解、代码生成、科学计算等多项基准超越 GPT-4',
      '向企业客户开放 API 接口，支持私有化部署',
      '与华为云深度集成，提供一站式 AI 开发平台',
    ],
    aiQuestions: [
      '与 GPT-5 相比有什么差距？',
      '对国内 AI 竞争格局有什么影响？',
      '企业如何接入使用？',
    ],
  },
]

/** 热门搜索词 */
export const HOT_SEARCH_WORDS = [
  'GPT-5', '美联储降息', '半导体', 'A股', '大模型',
  '华为', '招投标', 'AI政策', '新能源', '碳中和',
]
